ТЗ #1:1: Реализовать контролеры и модели для фильмов и пользователей
ir0nmand0/java-filmorate pull request #5
Opened 2024-04-27 07:39 UTC by ir0nmand0

Это была довольно насыщенная тема. Фреймворки упрощают написание кода, но сколько еще предстоит узнать.

2024-04-27 16:20 UTC, EugeneLenkevich commented
> Это была довольно насыщенная тема. Фреймворки упрощают написание кода, но сколько еще предстоит узнать.

Конечно, они для этого и существуют, особенно если вспомнить насколько сложнее руками те же  http-запросы писать. Сейчас мы приложения собирать из кирпичиков:)

2024-04-27 16:20 UTC, EugeneLenkevich requested changes
Привет! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2024-04-27 16:20 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        if (ObjectUtils.isEmpty(name)) {
Как то очень не очевидно тут состояние объекта менять, что то подсказывает что другие разработчики могут удивиться что set-метод устанавливает не то значение которое ему передали :)
А вот так логика в get-методе, которая подсовывает логин, может ее как и хватит для задуманного?

2024-04-27 16:20 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/ConditionsNotMetException.java
> +public class ConditionsNotMetException extends RuntimeException {
extends RuntimeException

А подходит ли для данной ситуации непроверяемое исключение?
Пользователь где то ввел некорректные данные и пр - вполне себе штатная ситуация, а что если это будет проверяемое исключение, как думаешь :)
extends Exception

2024-04-27 16:20 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .anyMatch(userName -> userName.trim().equalsIgnoreCase(user.getLogin().trim()));
.fiter(userName -> userName.trim().equalsIgnoreCase(user.getLogin().trim()))
.findFirst()
.orElseThrow(-> throw new ConditionsNotMetException(...))

Примерно так еще можно записать, то же самое, но слегка покороче  :)

2024-04-27 16:20 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (users.containsKey(user.getId())) {
users.containsKey(user.getId())

А вот смотри, если мы заведем такой метод вместо этого вызова

boolean isExist(userId)

То а) у нас появится семантика именно бизнес-логики б) мы спрячем детали реализации хранения данных, посмотри, может еще пару таких мест найдешь, это сделает наш код более выразительным ну и потом менять способ хранения данных можно будет проще :)

2024-04-27 17:17 UTC, ir0nmand0 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        if (ObjectUtils.isEmpty(name)) {
![image](https://github.com/ir0nmand0/java-filmorate/assets/153028067/ebcd5289-cab6-44a3-a17c-2f1c0c5a638a)

Так в ТЗ было написано, может я не прав с сетом, но мне показалось, что лучше и его переопределить. Если общая практика говорит, что лучше так не стоит делать, тогда изменю.

2024-04-27 17:23 UTC, ir0nmand0 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ConditionsNotMetException.java
> +public class ConditionsNotMetException extends RuntimeException {
![image](https://github.com/ir0nmand0/java-filmorate/assets/153028067/86943d07-d283-45a7-9e17-53500d4a1968)

Я точно так же думал...

2024-04-27 17:28 UTC, ir0nmand0 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ConditionsNotMetException.java
> +public class ConditionsNotMetException extends RuntimeException {
Все равно приходиться оборачивать при десериализации:
`            
if (releaseDate.isBefore(LocalDate.of(1895, 12, 28))) {
                try {
                    throw new ConditionsNotMetException("Дата релиза фильма должна быть после 28.12.1895");
                } catch (ConditionsNotMetException e) {
                    throw new RuntimeException(e);
                }
            }
`

2024-04-27 17:41 UTC, ir0nmand0 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .anyMatch(userName -> userName.trim().equalsIgnoreCase(user.getLogin().trim()));
Спасибо за совет 👍 
P.S. Честно сказать на Яве практики маловато постоянно переключаюсь между написанием скриптом на powershell, и bash по работе... До сих пор привыкаю к функциональному стилю.

2024-04-27 18:42 UTC, ir0nmand0 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ConditionsNotMetException.java
> +public class ConditionsNotMetException extends RuntimeException {
решил использовать IllegalArgumentException

2024-04-27 18:51 UTC, ir0nmand0 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .anyMatch(userName -> userName.trim().equalsIgnoreCase(user.getLogin().trim()));
пришлось добавить метод boolean dbIsEmpty(), так как если список пуст, будет выброшено исключение.

2024-04-28 02:40 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/ConditionsNotMetException.java
> +public class ConditionsNotMetException extends RuntimeException {
Оставил бы старый вариант :)

2024-04-28 02:53 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .anyMatch(userName -> userName.trim().equalsIgnoreCase(user.getLogin().trim()));
Тут следующая логика
isExist (user) - существует ли пользователь
isExist (userId) - существует ли пользователь по идентификатору
а вот если пишем 
idIsExist - идентификатор существует, даже не вопрос а утверждение (по правилам английского языка, а мы же по факту на нем тут и пишем) 

То есть, в идеале, код должен читаться как простой текст, основной смыл в этом. Но это немного забегая, потом мы будем  выделять сервисный слой, там это все будет наглядней :)

Функциональный стиль, кстати, работает аналогичным образом, мы оставляем суть, саму логику работы с объектами, но убираем все эти ветвления циклы и пр технические моменты которые могут мешать восприятию бизнес-логики. Но тут главное без фанатизма - стримы достаточно трудно дебажить, да и читать бывает трудновато такой код если стрим сильно навороченный :)

2024-04-28 02:54 UTC, EugeneLenkevich approved these changes
В целом все верно, задел небольшой на следующее задание :)

2024-04-28 05:10 UTC, ir0nmand0 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .anyMatch(userName -> userName.trim().equalsIgnoreCase(user.getLogin().trim()));
После курса по яве как раз хотел взять английский, увы слабая сторона.

2024-04-28 05:11 UTC, merged