ТЗ #2-1: Добавить реализацию лайков и друзей
ir0nmand0/java-filmorate pull request #6
Opened 2024-04-30 13:13 UTC by ir0nmand0

2024-04-30 17:25 UTC, EugeneLenkevich commented
> Решил построить большую часть хранения на set, очень удобная и быстрая [штука](https://gist.github.com/psayre23/c30a821239f4818b0709), которая вдобавок еще и дубликаты исключает.

Ну в целом да, но не совсем, HashSet быстрый, а вот другие реализации могут быть не особо производительными :)
В СУБД индексы в принципе +/- по тем же принципам работают: когда их нет мы ищем по всему списку через full-scan, а если есть подходящий индекс - то по нему как в картотеке библиотеки, где все шкафы пронумерованы по алфавиту. Немножко грубая аналогия, но в целом как то так :)

> P.S. Обрати внимание на «костыль» из-за ошибочного теста postman [«Not friend remove»,](https://github.com/yandex-praktikum/java-filmorate/blob/add-friends-likes/postman/sprint.json#L1095) ожидается код 200, когда по моему мнению должен быть 400, если я не прав, то исправлю, пока что никуда не сообщал об этом.

2024-04-30 17:52 UTC, EugeneLenkevich requested changes
Привет! Спасибо за PR.

Работа хорошая, видно что заморочился :)
Давай только еще доработаем распределение обязанностей между слоями. Все что касается хранения данных: выборка сортировка, фильтрация и пр - в хранилище, все что касается именно бизнес логики - в сервис, причем семантика в каждом слое лучше чтобы была соответствующая. Поразмышляй, как можно это сделать и обрати внимание как код становится самодокументируемым если придерживаться этого правила :)
Далее мы как раз будем переделывать слой хранения данных, тоже увидим как это влияет на поддерживаемость кода

2024-04-30 17:52 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/PostmanNotFriendRemoveException.java
> + */
А почему ошибка, не факт, может наоборот такое поведение по какой то причине подходит :)
Сам подход норм, пусть так и будет

2024-04-30 17:52 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/film/InMemoryFilmService.java
> +    private final TreeMap<Integer, Set<Long>> numberOfLikes = new TreeMap<>(Collections.reverseOrder());
TreeMap кстати медленная достаточно, если что

2024-04-30 17:52 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/film/InMemoryFilmService.java
> +        numberOfLikes.get(oldSize).remove(id);
numberOfLikes.get(oldSize).remove(id)

Так и хочется эту логику спрятать в хранилища метод, к тому же подобный код вижу несколько раз повторяется. Пролезают  детали реализации, лучше их скрыть, код так проще будет. Вообще, на уровне сервисов мы пользуемся терминологией бизнес-логики, потому чем больше у нас будет бизнес-глаголов (методов) тем наш код будет проще и, самое важное,  он будет самодокументирован, его можно будет читать просто как текст, ну, в идеальном случае, конечно, но тем не менее стремиться к этому стоит  :) 

Вообще, по классике, ответственность по слоям распределяется вот так

> Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.
> 
> Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.
> 
> Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса.

2024-04-30 17:52 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!films.containsKey(id)) {
А что если создать метод хранилища isExist(id), кажется что код станет более очевидным :)

2024-04-30 17:52 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User extends Id {
User extends Id

"Пользователь наследуется от идентификатора", с точки зрения компьютера конечно норм, ему без разницы, но с семантической точки зрения звучит это как то странно, так и хочется базовый класс, например, переименовать :)

2024-04-30 17:52 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Id.java
> +        long currentMaxId = map.keySet().stream()
Тут у нас сущность лезет в обязанности, наверное, хранилища и управляет генерацией идентификаторов. Наверное это не очень хорошо с точки зрения распределения обязанностей, это же относится к хранению данных, будь то бы выглядит более логично если хранилище само будет заниматься этим распределением. В общем каким то бы образом убрать бы из сущности эту обязанность :)

2024-04-30 18:52 UTC, ir0nmand0 commented on src/main/java/ru/yandex/practicum/filmorate/model/Id.java
> +        long currentMaxId = map.keySet().stream()
Исключил класс Id полностью. Перенес это поле в классы фильмы и пользователи.

2024-04-30 18:55 UTC, ir0nmand0 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/InMemoryFilmService.java
> +    private final TreeMap<Integer, Set<Long>> numberOfLikes = new TreeMap<>(Collections.reverseOrder());
Насчет скорости в курсе, но так уже список всегда отсортирован, у каждого решения есть свои минусы, либо сортировать сразу, либо потом... Может есть третий путь, но пока он не ясен.

2024-04-30 20:33 UTC, ir0nmand0 commented
Вроде все исправил, надеюсь теперь будет лучше, а не [так](https://github.com/ir0nmand0/java-filmorate/assets/153028067/1932c46f-a8af-41e7-ba3e-2c633f8910d2)

Источник: https://t.me/it_dad/3758

2024-05-01 03:19 UTC, EugeneLenkevich requested changes
На самом деле это очень не просто сходу разделить бизнес-логику и хранение данных :)

Сейчас методы просто переехали в сторедж. Давай еще раз попробуем, но подход выберем другой: оставим наши методы как есть в сервисе, но все обращения к мапам с данными заменим соответствующими вызовами хранилища. По идее тогда у нас и должно получится то что надо

Другими словами
1. Если мы говорим что то типа "надо пойтив мапу А" и пр -  скорее всего это обязанность хранилища и это стоит заменить на метод хранилища
2. По сути дела методы хранилища должны выглядеть так : "берем мапу А, фильтруем ее/берем из нее записи/возвращаем элемент по id" и пр. Если что то больше получается какие то условия появляются - скорее всего это обязанности сервиса и стоить что то  вынести в него
3. Методы сервиса будут выглядеть как инструкции из реальной жизни, как например инструкция к бытовой технике или рецепт блюда. Если мы, например, варим гречу, то в сервисе мы ее просто "берем" из хранилища - какой то банки, а вот что именно там за банка на уровне рецепта не имеет значения, вот тут как то так же :) 
4. И еще, если у нас правильно разделены обязанности то мы будем иметь возможность с минимальными доработками заменить хранилище на другое, на это то же можно ориентирроваться. Для того же рецепта не важно откуда греча - из жестяной банки, из кулька или вообще по трубке ее насыпают, вот тут примерно так же 

Давай быстренько метод-другой для закрепления попробуем разбить по такой логике, c этим лучше сразу до конца разобраться чтобы потом не страдать :)

2024-05-01 03:19 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        findOrElseThrow(id);
Тут и в методе ниже похоже тоже бизнес-логика попала.
Как минимум логирование лучше в сервис оставить, в нем же прямым текстом идет описание именно бизнеc-логики :)

2024-05-01 03:31 UTC, EugeneLenkevich commented
> Вроде все исправил, надеюсь теперь будет лучше, а не [так](https://github.com/ir0nmand0/java-filmorate/assets/153028067/1932c46f-a8af-41e7-ba3e-2c633f8910d2)
> 
> Источник: https://t.me/it_dad/3758

Это все другое, у нас тут нормальный код, просто у нас сейчас есть возможность заморочиться и ковыряться. А видос про реальный проект, когда что то пилили в спешке :) 

> Вроде все исправил, надеюсь теперь будет лучше, а не [так](https://github.com/ir0nmand0/java-filmorate/assets/153028067/1932c46f-a8af-41e7-ba3e-2c633f8910d2)
> 
> Источник: https://t.me/it_dad/3758

Да ладно, нормальный код, просто у нас есть возможность заморочиться, поковыряться и сделать лучше.

Но, вообще, всегда и везде есть такие коллеги как в видосе которым все не нравится :)

2024-05-01 08:06 UTC, ir0nmand0 commented
Надеюсь, мне удалось изменить как надо… Я думаю, теперь максимально адаптировал под SQL для следующего ТЗ, но не до конца, так как пока что еще есть разрыв в знаниях, да и особенность хранения никто не отменял (к примеру, хранение размера лайков, как идентификатор для treeMap при добавлении или удалении лайков).

2024-05-01 12:25 UTC, EugeneLenkevich approved these changes
Ок, супер, спасибо, пусть пока так будет, дальше посмотрим как будет :)

2024-05-01 12:44 UTC, merged